version: '3'

volumes:
  local_postgres_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: invencloud_local_django
    container_name: invencloud_local_django
    environment:
      - TAKE_DOCKER_ENVS=1
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    entrypoint: ["./compose/local/django/entrypoint.sh"]
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  postgres:
    image: postgres:16
    container_name: invencloud_local_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: invencloud
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

networks:
  default:
    driver: bridge
