version: '3'

volumes:
  local_postgres_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: invencloud_local_django
    container_name: invencloud_local_django
    environment:
      - TAKE_DOCKER_ENVS=1
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    entrypoint: ["./compose/production/django/entrypoint.sh"]
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

networks:
  default:
    driver: bridge
